In [1]:
import pandas as pd

sales = pd.read_csv("./sales_cleaned.csv")

In [2]:
sales.head()

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp,Year,Month,MonthName
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09 20:21:00,2024,8,August
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28 05:01:00,2024,11,November
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13 00:36:00,2024,10,October
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,1015.07,50.0,2024-07-06 23:39:00,2024,7,July
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08 19:58:00,2024,6,June

In [3]:
sales['Timestamp'] = pd.to_datetime(sales['Timestamp'])

In [4]:
dim_date = pd.DataFrame()

dim_date['FullDate'] = sales['Timestamp'].dt.date
dim_date['Month'] = sales['Timestamp'].dt.month
dim_date['MonthName'] = sales['Timestamp'].dt.month_name()
dim_date['Year'] = sales['Timestamp'].dt.year

In [5]:
# Remove duplicates
dim_date = dim_date.drop_duplicates().reset_index(drop=True)

# Generate DateID
dim_date.insert(0, 'DateID', range(1, len(dim_date) + 1))

In [6]:
dim_date.head()

   DateID    FullDate  Month MonthName  Year
0       1  2024-08-09      8    August  2024
1       2  2024-11-28     11  November  2024
2       3  2024-10-13     10   October  2024
3       4  2024-07-06      7      July  2024
4       5  2024-06-08      6      June  2024

In [7]:
dim_date.to_csv("dim_date.csv", index=False)

In [8]:
sales.head()

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp,Year,Month,MonthName
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09 20:21:00,2024,8,August
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28 05:01:00,2024,11,November
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13 00:36:00,2024,10,October
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,1015.07,50.0,2024-07-06 23:39:00,2024,7,July
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08 19:58:00,2024,6,June

In [9]:
sales['FullDate'] = sales['Timestamp'].dt.date

sales = sales.merge(
    dim_date[['DateID', 'FullDate']],
    on='FullDate',
    how='left'
)

In [10]:
sales[['Timestamp', 'DateID']].head()

            Timestamp  DateID
0 2024-08-09 20:21:00       1
1 2024-11-28 05:01:00       2
2 2024-10-13 00:36:00       3
3 2024-07-06 23:39:00       4
4 2024-06-08 19:58:00       5

In [13]:
sales.head()

,SaleID,ProductID,CustomerID,SalesAmount,Quantity,Timestamp,Year,Month,MonthName,FullDate,DateID
0,c0078cd1-3ddc-439a-b41d-7498e8e75e62,1020,C0460,1639.10,18.0,2024-08-09 20:21:00,2024,8,August,2024-08-09,1
1,be8532af-16b7-432c-a13d-4c6e6836d12d,1029,C0198,186.11,42.0,2024-11-28 05:01:00,2024,11,November,2024-11-28,2
2,8666f277-cc58-4fde-9d58-697da9e040f2,1012,C0524,1712.72,49.0,2024-10-13 00:36:00,2024,10,October,2024-10-13,3
3,383e0a2b-7e00-454e-a269-b2f73ecd33f2,1016,C0285,1015.07,50.0,2024-07-06 23:39:00,2024,7,July,2024-07-06,4
4,d9a7f974-9572-48dd-aa36-3f96b280dfc7,1021,C0369,66.36,21.0,2024-06-08 19:58:00,2024,6,June,2024-06-08,5

In [14]:
fact_sales = sales[
    [
        'SaleID',
        'CustomerID',
        'ProductID',
        'DateID',
        'Quantity',
        'SalesAmount'
    ]
]

In [16]:
fact_sales.to_csv(
    "fact_sales23.csv",
    index=False
)