# Employee Performance and Attrition Analysis

## Chapter 2 – Dataset Understanding and Initial Data Inspection

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
employee_df = pd.read_csv("employee_data 1.csv")
attrition_df = pd.read_csv("Attrition 1.csv")
performance_df = pd.read_csv("employee_performance_data 1.csv")

In [3]:
print("Employee Data Shape:", employee_df.shape)
print("Attrition Data Shape:", attrition_df.shape)
print("Employee Performance Data Shape:", performance_df.shape)

Employee Data Shape: (1000, 12)
Attrition Data Shape: (144, 3)
Employee Performance Data Shape: (1000, 6)

In [4]:
print("Employee Data Columns:")
print(employee_df.columns.tolist())

print("\nAttrition Data Columns:")
print(attrition_df.columns.tolist())

print("\nEmployee Performance Data Columns:")
print(performance_df.columns.tolist())

Employee Data Columns:
['Employee_ID', 'Age', 'first_name', 'last_name', 'gender', 'Gender', 'Department', 'Job_Role', 'Education_Level', 'Marital_Status', 'Job_Tenure', 'Distance_From_Home']

Attrition Data Columns:
['employee_ID', 'attrition', 'Exit_Interview_Score']

Employee Performance Data Columns:
['Employee_ID', 'Performance_Rating', 'Last_Promotion_Year', 'Training_Hours', 'Work_Life_Balance', 'Job_Satisfaction']

In [5]:
print("Employee Data")
display(employee_df.head())

print("Attrition Data")
display(attrition_df.head())

print("Employee Performance Data")
display(performance_df.head())

Employee Data

,Employee_ID,Age,first_name,last_name,gender,Gender,Department,Job_Role,Education_Level,Marital_Status,Job_Tenure,Distance_From_Home
0,1,22,Konstantin,Shutler,Male,Other,HR,Developer,PhD,Married,1,8
1,2,38,Thorvald,Skoggins,Male,Other,IT,Marketing Lead,Master's,Married,18,32
2,3,35,Gracia,Teggin,Genderqueer,Male,Sales,Senior Developer,Bachelor's,Divorced,4,42
3,4,37,Kerwinn,Romme,Male,Male,Marketing,Senior Developer,Bachelor's,Divorced,5,43
4,5,26,Randene,Millier,Female,Female,Operations,Manager,Master's,Single,10,33

Attrition Data

   employee_ID  attrition  Exit_Interview_Score
0          474       True                     2
1           97       True                     4
2          729      False                     1
3          278      False                     2
4          470      False                     4

Employee Performance Data

,Employee_ID,Performance_Rating,Last_Promotion_Year,Training_Hours,Work_Life_Balance,Job_Satisfaction
0,1,2,2019,28,3,1
1,2,4,2022,174,3,2
2,3,1,2022,119,5,4
3,4,4,2015,82,4,1
4,5,3,2014,46,2,4

In [6]:
print("Employee Data Information")
employee_df.info()

print("\nAttrition Data Information")
attrition_df.info()

print("\nEmployee Performance Data Information")
performance_df.info()

Employee Data Information
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         1000 non-null   int64
 1   Age                 1000 non-null   int64
 2   first_name          1000 non-null   str
 3   last_name           1000 non-null   str
 4   gender              1000 non-null   str
 5   Gender              1000 non-null   str
 6   Department          1000 non-null   str
 7   Job_Role            1000 non-null   str
 8   Education_Level     1000 non-null   str
 9   Marital_Status      1000 non-null   str
 10  Job_Tenure          1000 non-null   int64
 11  Distance_From_Home  1000 non-null   int64
dtypes: int64(4), str(8)
memory usage: 93.9 KB

Attrition Data Information
<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_ID           144 non-null    int64
 1   attrition             144 non-null    bool
 2   Exit_Interview_Score  144 non-null    int64
dtypes: bool(1), int64(2)
memory usage: 2.5 KB

Employee Performance Data Information
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          1000 non-null   int64
 1   Performance_Rating   1000 non-null   int64
 2   Last_Promotion_Year  1000 non-null   int64
 3   Training_Hours       1000 non-null   int64
 4   Work_Life_Balance    1000 non-null   int64
 5   Job_Satisfaction     1000 non-null   int64
dtypes: int64(6)
memory usage: 47.0 KB

In [8]:
print("Missing Values in Employee Data")
print(employee_df.isnull().sum())

print("\nMissing Values in Attrition Data")
print(attrition_df.isnull().sum())

print("\nMissing Values in Employee Performance Data")
print(performance_df.isnull().sum())

Missing Values in Employee Data
Employee_ID           0
Age                   0
first_name            0
last_name             0
gender                0
Gender                0
Department            0
Job_Role              0
Education_Level       0
Marital_Status        0
Job_Tenure            0
Distance_From_Home    0
dtype: int64

Missing Values in Attrition Data
employee_ID             0
attrition               0
Exit_Interview_Score    0
dtype: int64

Missing Values in Employee Performance Data
Employee_ID            0
Performance_Rating     0
Last_Promotion_Year    0
Training_Hours         0
Work_Life_Balance      0
Job_Satisfaction       0
dtype: int64

In [9]:
print("Duplicate records in Employee Data:", employee_df.duplicated().sum())
print("Duplicate records in Attrition Data:", attrition_df.duplicated().sum())
print("Duplicate records in Employee Performance Data:", performance_df.duplicated().sum())

Duplicate records in Employee Data: 0
Duplicate records in Attrition Data: 2
Duplicate records in Employee Performance Data: 0

In [10]:
print("Employee Data ID column:")
print(employee_df.columns.tolist())

print("\nAttrition Data ID column:")
print(attrition_df.columns.tolist())

print("\nPerformance Data ID column:")
print(performance_df.columns.tolist())

Employee Data ID column:
['Employee_ID', 'Age', 'first_name', 'last_name', 'gender', 'Gender', 'Department', 'Job_Role', 'Education_Level', 'Marital_Status', 'Job_Tenure', 'Distance_From_Home']

Attrition Data ID column:
['employee_ID', 'attrition', 'Exit_Interview_Score']

Performance Data ID column:
['Employee_ID', 'Performance_Rating', 'Last_Promotion_Year', 'Training_Hours', 'Work_Life_Balance', 'Job_Satisfaction']

Check Employee ID Uniqueness

In [11]:
print("Unique Employee IDs:", employee_df["Employee_ID"].nunique())
print("Total Employee Records:", len(employee_df))

print("\nUnique Performance Employee IDs:", performance_df["Employee_ID"].nunique())
print("Total Performance Records:", len(performance_df))

print("\nUnique Attrition Employee IDs:", attrition_df["employee_ID"].nunique())
print("Total Attrition Records:", len(attrition_df))

Unique Employee IDs: 1000
Total Employee Records: 1000

Unique Performance Employee IDs: 1000
Total Performance Records: 1000

Unique Attrition Employee IDs: 127
Total Attrition Records: 144

Check Duplicate

In [12]:
attrition_duplicates = attrition_df[
    attrition_df.duplicated(keep=False)
]

display(attrition_duplicates)

     employee_ID  attrition  Exit_Interview_Score
14           742      False                     3
58           561      False                     2
82           742      False                     3
119          561      False                     2

Check Whether Attrition Employee IDs Repeat

In [13]:
attrition_id_counts = attrition_df["employee_ID"].value_counts()

print("Employees appearing more than once in Attrition Data:")
display(attrition_id_counts[attrition_id_counts > 1])

Employees appearing more than once in Attrition Data:

employee_ID
97     2
897    2
790    2
253    2
742    2
684    2
929    2
556    2
640    2
561    2
262    2
357    2
959    2
216    2
272    2
129    2
213    2
Name: count, dtype: int64

Analyze Attrition Status

In [14]:
print("Attrition Status Distribution:")
print(attrition_df["attrition"].value_counts())

print("\nAttrition Status Percentage:")
print(attrition_df["attrition"].value_counts(normalize=True) * 100)

Attrition Status Distribution:
attrition
False    74
True     70
Name: count, dtype: int64

Attrition Status Percentage:
attrition
False    51.388889
True     48.611111
Name: proportion, dtype: float64

Investigate gender vs Gender

In [15]:
print("Unique values in gender:")
print(employee_df["gender"].value_counts())

print("\nUnique values in Gender:")
print(employee_df["Gender"].value_counts())

Unique values in gender:
gender
Female         453
Male           442
Bigender        21
Agender         21
Non-binary      19
Genderqueer     16
Genderfluid     16
Polygender      12
Name: count, dtype: int64

Unique values in Gender:
Gender
Other     343
Female    336
Male      321
Name: count, dtype: int64

In [16]:
print("Number of records where gender and Gender are different:",
      (employee_df["gender"] != employee_df["Gender"]).sum())

Number of records where gender and Gender are different: 706

Check Employee ID Coverage Across Datasets
We need to determine which employee IDs in Attrition Data actually exist in Employee Data.

In [17]:
employee_ids = set(employee_df["Employee_ID"])
attrition_ids = set(attrition_df["employee_ID"])
performance_ids = set(performance_df["Employee_ID"])

print("Attrition IDs found in Employee Data:",
      len(attrition_ids.intersection(employee_ids)))

print("Attrition IDs NOT found in Employee Data:",
      len(attrition_ids - employee_ids))

print("Performance IDs found in Employee Data:",
      len(performance_ids.intersection(employee_ids)))

print("Performance IDs NOT found in Employee Data:",
      len(performance_ids - employee_ids))

Attrition IDs found in Employee Data: 127
Attrition IDs NOT found in Employee Data: 0
Performance IDs found in Employee Data: 1000
Performance IDs NOT found in Employee Data: 0

Check Missing Employee IDs

In [18]:
missing_attrition_ids = attrition_ids - employee_ids
missing_performance_ids = performance_ids - employee_ids

print("Missing Attrition Employee IDs:")
print(missing_attrition_ids)

print("\nMissing Performance Employee IDs:")
print(missing_performance_ids)

Missing Attrition Employee IDs:
set()

Missing Performance Employee IDs:
set()

employee IDs in the child datasets exist in the Employee dataset.

Investigate Repeated Attrition Records

In [20]:
repeated_ids = repeated_attrition_ids.index

repeated_attrition_records = attrition_df[
    attrition_df["employee_ID"].isin(repeated_ids)
].sort_values("employee_ID")

display(repeated_attrition_records)

     employee_ID  attrition  Exit_Interview_Score
1             97       True                     4
100           97       True                     2
107          129      False                     4
127          129      False                     5
121          213       True                     4
139          213      False                     2
93           216       True                     1
76           216       True                     2
45           253      False                     4
13           253       True                     5
62           262      False                     4
105          262      False                     3
142          272       True                     1
86           272       True                     4
66           357       True                     5
67           357      False                     2
68           556       True                     4
36           556      False                     5
119          561      False                     2
58           561      False                     2
41           640      False                     2
94           640      False                     3
15           684       True                     3
57           684       True                     2
82           742      False                     3
14           742      False                     3
7            790       True                     1
101          790       True                     2
28           897       True                     2
6            897      False                     4
38           929       True                     2
30           929      False                     4
75           959       True                     3
89           959       True                     5

In [21]:
# Check conflicts 
attrition_conflicts = (
    repeated_attrition_records
    .groupby("employee_ID")
    .agg(
        record_count=("employee_ID", "size"),
        attrition_values=("attrition", lambda x: list(x)),
        exit_scores=("Exit_Interview_Score", lambda x: list(x))
    )
    .reset_index()
)

display(attrition_conflicts)

    employee_ID  record_count attrition_values exit_scores
0            97             2     [True, True]      [4, 2]
1           129             2   [False, False]      [4, 5]
2           213             2    [True, False]      [4, 2]
3           216             2     [True, True]      [1, 2]
4           253             2    [False, True]      [4, 5]
5           262             2   [False, False]      [4, 3]
6           272             2     [True, True]      [1, 4]
7           357             2    [True, False]      [5, 2]
8           556             2    [True, False]      [4, 5]
9           561             2   [False, False]      [2, 2]
10          640             2   [False, False]      [2, 3]
11          684             2     [True, True]      [3, 2]
12          742             2   [False, False]      [3, 3]
13          790             2     [True, True]      [1, 2]
14          897             2    [True, False]      [2, 4]
15          929             2    [True, False]      [2, 4]
16          959             2     [True, True]      [3, 5]

In [22]:
# Investigate gender and Gender
gender_comparison = pd.crosstab(
    employee_df["gender"],
    employee_df["Gender"]
)

display(gender_comparison)

Gender       Female  Male  Other
gender
Agender           6     9      6
Bigender          9     8      4
Female          155   145    153
Genderfluid       9     3      4
Genderqueer       5     6      5
Male            141   139    162
Non-binary        6     7      6
Polygender        5     4      3

In [23]:
# Checking Missing or blank value
print("Blank gender values:",
      (employee_df["gender"].astype(str).str.strip() == "").sum())

print("Blank Gender values:",
      (employee_df["Gender"].astype(str).str.strip() == "").sum())

Blank gender values: 0
Blank Gender values: 0

In [24]:
# Create a Data Quality Summary
data_quality_summary = pd.DataFrame({
    "Dataset": [
        "Employee Data",
        "Attrition Data",
        "Employee Performance Data"
    ],
    "Rows": [
        len(employee_df),
        len(attrition_df),
        len(performance_df)
    ],
    "Columns": [
        len(employee_df.columns),
        len(attrition_df.columns),
        len(performance_df.columns)
    ],
    "Missing Values": [
        employee_df.isnull().sum().sum(),
        attrition_df.isnull().sum().sum(),
        performance_df.isnull().sum().sum()
    ],
    "Duplicate Rows": [
        employee_df.duplicated().sum(),
        attrition_df.duplicated().sum(),
        performance_df.duplicated().sum()
    ],
    "Unique Employee IDs": [
        employee_df["Employee_ID"].nunique(),
        attrition_df["employee_ID"].nunique(),
        performance_df["Employee_ID"].nunique()
    ]
})

display(data_quality_summary)

,Dataset,Rows,Columns,Missing Values,Duplicate Rows,Unique Employee IDs
0,Employee Data,1000,12,0,0,1000
1,Attrition Data,144,3,0,2,127
2,Employee Performance Data,1000,6,0,0,1000

In [25]:
# Performing cleaning in copy Dataset
employee_clean = employee_df.copy()
attrition_clean = attrition_df.copy()
performance_clean = performance_df.copy()

print("Working copies created successfully.")

Working copies created successfully.

In [26]:
# Standardize Employee Column Names

employee_clean = employee_clean.rename(columns={
    "first_name": "First_Name",
    "last_name": "Last_Name",
    "gender": "Gender_Detailed",
    "Gender": "Gender_Group"
})

print(employee_clean.columns.tolist())

['Employee_ID', 'Age', 'First_Name', 'Last_Name', 'Gender_Detailed', 'Gender_Group', 'Department', 'Job_Role', 'Education_Level', 'Marital_Status', 'Job_Tenure', 'Distance_From_Home']

In [27]:
# Standardize Attrition Column Names
attrition_clean = attrition_clean.rename(columns={
    "employee_ID": "Employee_ID"
})

print(attrition_clean.columns.tolist())

['Employee_ID', 'attrition', 'Exit_Interview_Score']

In [28]:
attrition_clean = attrition_clean.rename(columns={
    "attrition": "Attrition"
})

print(attrition_clean.columns.tolist())

['Employee_ID', 'Attrition', 'Exit_Interview_Score']

In [29]:
performance_clean.columns.tolist()

['Employee_ID',
 'Performance_Rating',
 'Last_Promotion_Year',
 'Training_Hours',
 'Work_Life_Balance',
 'Job_Satisfaction']

## Remove Only Exact Duplicate Attrition Rows

In [30]:
before_duplicates = len(attrition_clean)

attrition_clean = attrition_clean.drop_duplicates()

after_duplicates = len(attrition_clean)

print("Records before duplicate removal:", before_duplicates)
print("Records after duplicate removal:", after_duplicates)
print("Exact duplicate records removed:", before_duplicates - after_duplicates)

Records before duplicate removal: 144
Records after duplicate removal: 142
Exact duplicate records removed: 2

In [31]:
print("Employee Data")
print("Rows:", len(employee_clean))
print("Duplicate rows:", employee_clean.duplicated().sum())

print("\nAttrition Data")
print("Rows:", len(attrition_clean))
print("Duplicate rows:", attrition_clean.duplicated().sum())

print("\nPerformance Data")
print("Rows:", len(performance_clean))
print("Duplicate rows:", performance_clean.duplicated().sum())

Employee Data
Rows: 1000
Duplicate rows: 0

Attrition Data
Rows: 142
Duplicate rows: 0

Performance Data
Rows: 1000
Duplicate rows: 0

In [32]:
print("Employee Data Missing Values:")
print(employee_clean.isnull().sum().sum())

print("\nAttrition Data Missing Values:")
print(attrition_clean.isnull().sum().sum())

print("\nPerformance Data Missing Values:")
print(performance_clean.isnull().sum().sum())

Employee Data Missing Values:
0

Attrition Data Missing Values:
0

Performance Data Missing Values:
0

In [33]:
# Validate the Employee Relationships Again

employee_ids = set(employee_clean["Employee_ID"])
attrition_ids = set(attrition_clean["Employee_ID"])
performance_ids = set(performance_clean["Employee_ID"])

print("Attrition IDs not found in Employee Data:",
      len(attrition_ids - employee_ids))

print("Performance IDs not found in Employee Data:",
      len(performance_ids - employee_ids))

Attrition IDs not found in Employee Data: 0
Performance IDs not found in Employee Data: 0

In [37]:
# employee_clean.head()
# attrition_clean.head()
performance_clean.head()

,Employee_ID,Performance_Rating,Last_Promotion_Year,Training_Hours,Work_Life_Balance,Job_Satisfaction
0,1,2,2019,28,3,1
1,2,4,2022,174,3,2
2,3,1,2022,119,5,4
3,4,4,2015,82,4,1
4,5,3,2014,46,2,4

In [38]:
final_quality_summary = pd.DataFrame({
    "Dataset": [
        "Employee Data",
        "Attrition Data",
        "Employee Performance Data"
    ],
    "Original Rows": [
        len(employee_df),
        len(attrition_df),
        len(performance_df)
    ],
    "Final Rows": [
        len(employee_clean),
        len(attrition_clean),
        len(performance_clean)
    ],
    "Columns": [
        len(employee_clean.columns),
        len(attrition_clean.columns),
        len(performance_clean.columns)
    ],
    "Missing Values": [
        employee_clean.isnull().sum().sum(),
        attrition_clean.isnull().sum().sum(),
        performance_clean.isnull().sum().sum()
    ],
    "Duplicate Rows": [
        employee_clean.duplicated().sum(),
        attrition_clean.duplicated().sum(),
        performance_clean.duplicated().sum()
    ]
})

display(final_quality_summary)

,Dataset,Original Rows,Final Rows,Columns,Missing Values,Duplicate Rows
0,Employee Data,1000,1000,12,0,0
1,Attrition Data,144,142,3,0,0
2,Employee Performance Data,1000,1000,6,0,0

In [39]:
employee_clean.to_csv("employee_cleaned.csv", index=False)
attrition_clean.to_csv("attrition_cleaned.csv", index=False)
performance_clean.to_csv("employee_performance_cleaned.csv", index=False)

print("Cleaned datasets saved successfully.")

Cleaned datasets saved successfully.